/*
Banco - OBI 2012 - Fase 2 - Nível 2
Carlos Eduardo de Santana Bastos
IFPI - Campus São Raimundo Nonato
*/

#include <bits/stdc++.h>

using namespace std;

int main(int argc, char const *argv[])
{
	//Fila de prioridade para guardar qual caixa desocupa primeiro...
	priority_queue<int, vector<int>, greater<int> > caixas;
	int C, N, T, D, r = 0;
	cin >> C >> N;
	//Todos os caixas começam vazios!
	for (int i = 0; i < C; ++i)
		caixas.push(0);
	//Para cada cliente...
	for (int i = 0; i < N; ++i)
	{
		//Pega a hora de entrada e a duração do atendimento...
		cin >> T >> D;
		//Pego a hora que ele foi atendido...
		//No caso é a hora que o primeiro caixa ficou livre...
		int hora_atendimento = caixas.top();
		//Tiro aquele caixa da fila...
		caixas.pop();
		//Calculo o tempo de espera que o cliente ficou esperando...
		//Baseado na hora que ele foi atendido e na hora que ele chegou...
		int tempo_espera = hora_atendimento - T;
		//Se o cliente demorou mais de 20 minutos, aumenta em 1 unidade a minha resposta...
		if(tempo_espera > 20)
			r++;
		//No final coloca o meu caixa na fila novamente...
		//Atualizando o seu novo horário no qual ficará livre...
		//Sendo este, o máximo entre, a hora que ele ficou livre + a duração do atendimento...
		//Ou a hora que o cliente entrou mais a duração do atendimento...
		//Pois caso o caixa tenha ficado livre e nenhum cliente estava esperando...
		//A hora que ele vai desocupar é a duração mais o hora que o cliente chegou...
		//Senão, vai ser a hora que ele desocupou mais a duração...
		caixas.push(D + max(hora_atendimento, T));
	}

	cout << r << endl;
	return 0;
}